version: '3.9'
services:
  frontend:
    container_name: frontend
    build: ./front-end/
    ports:
      - 3000:3000
    platform: linux/x86_64
    working_dir: /frontend
    depends_on:
      backend:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "lsof", "-t", "-i:3000"]
      timeout: 10s
      retries: 5
  backend:
    container_name: backend
    build: ./back-end/
    ports:
      - 3001:3001
    platform: linux/x86_64
    working_dir: /backend
    command: npm run dev
    depends_on:
      database:
        condition: service_healthy
    environment:
      - PORT=3001
      - JWT_SECRET=jwtSecret
      - MYSQL_USER=root
      - MYSQL_PASSWORD=123456
      - MYSQL_DB_NAME=delivery-app
      - MYSQL_HOST=database
      - HOSTNAME=database
      - MYSQL_PORT=3306
    healthcheck:
      test: ["CMD", "lsof", "-t", "-i:3001"]
      timeout: 10s
      retries: 5
  database:
    image: mysql:8.0.21
    container_name: database
    platform: linux/x86_64
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    restart: 'always'
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 10s
      retries: 5
    cap_add:
      - SYS_NICE
